### ISSUE TITLE
TimerTrigger firing twice

### ISSUE THREAD

**Issue by mattwoberts** [Azure/azure-webjobs-sdk-extensions#106]
I've created a new TimerTrigger:

`public static void ExecuteDailySlackSummary([TimerTrigger("10 0 8 * * *", RunOnStartup = false, UseMonitor = false)] TimerInfo timerInfo, TextWriter log)`

But, sometimes, most times actually, the function fires twice.

The only thing "special" about this function, is that there is another TimerTrigger function running in the same webjob that runs from 9am, and usually is still running when this one fires up - if that's relevant.

Thanks

**Comment by mathewc** [comment]
What version of the Extensions package are you using - the RTM 1.0.1 version?

**Comment by mattwoberts** [comment]
The latest one in nuget is the one I'm using.

**Comment by christopheranderson** [comment]
Would you mind please looking at the version in the Packages.config file and tell us so we can be sure?

**Comment by mathewc** [comment]
We've made a lot of fixes to TimerTrigger, but those haven't RTM'ed yet. They're available in the latest prerelease version on myget (instructions [here](https://github.com/Azure/azure-webjobs-sdk/wiki/%22Nightly%22-Builds)), We'll get the prerelease up on nuget soon. If you like, you could try the latest bits and see. Others were reporting issues like this, and have confirmed that the prerelease version addressed them.

**Comment by mattwoberts** [comment]
I can't do this till Monday but will check what version I'm on then, and try the myget version

**Comment by mattwoberts** [comment]
HI,

I've upgraded to use the latest version from myget:

```
<package id="Microsoft.Azure.WebJobs.Core" version="2.0.0-alpha-10331" targetFramework="net461" />
<package id="Microsoft.Azure.WebJobs.Extensions" version="2.0.0-alpha-10306" targetFramework="net461" />

```

However, I'm still finding that this timertrigger is firing twice.

`public static void ExecuteDailySlackSummary([TimerTrigger("10 0 8 * * *", RunOnStartup = false)] TimerInfo timerInfo, TextWriter log)`

Are there any logs or anything else I can do to help troubleshoot this?

**Comment by mattwoberts** [comment]
Oddly, here's another TimerTrigger that I have, that doesn't exhibit the same behavior, it seems to work without issue:

'public static void ExecuteSlackPostJob([TimerTrigger("20 0 * * * *", RunOnStartup = false)] TimerInfo timerInfo, TextWriter log)'

They both live in the same project.

**Comment by mattwoberts** [comment]
Just to update again, it seems most of my TimerTriggers are doing this now :(

In addition, they're also running at what seems to be random timings - sometimes caused by me releasing via swapping slots, or from website restarts....

Can you let me know what I can do to help, I'd love to get to the bottom of this

**Comment by mattwoberts** [comment]
*bump* Can anyone help?

**Comment by mathewc** [comment]
I'll try to repro this morning using your above function definitions. One thing I notice is that your CRON expressions might not be doing what you expect. E.g. "20 0 * * * *" will run whenever the seconds are 20 and the minutes are 0, e.g. at 9:00:20, 10:00:20, etc. Is that your intent? Also for that function it looks like you have UseScheduleMonitor = true, so if for any reason your timer gets behind schedule, it will run immediately on startup to "catch up". If this is happening, the log entry should indicate that.

What is your assembly naming/versioning strategy for your JobHost? Host identity is based on the fully qualified assembly name of the exe by default (you can override this easily via JobHostConfiguration.HostId). The reason that might matter is because if you're revving the assembly version each time you build, and you have multiple instances running in different slots, they'll all be running at the same time, not coordinated via locks as is the case normally, since each host would have its own identity and would be using its own lock.

**Comment by mattwoberts** [comment]
Hi,

To answer your questions / hopefully shed more light:

1) CRON expressions - yes that's right - I have  a "20 0 * * * *" that runs on the hour (20 secs in), and another one that's "10 0 8 * * *" that's every day at 8am (UTC). This second one is the one that keeps repeating.

2) I've not added verbose logging to see what's happening, but I"ll add that

More info about my web job:

I've got about 7 TimerTrigger functions in my webjob. I've not done anything with the host identity configuration, so it's whatever the default is. My AssemblyVersion isn't changing much either - my AssemblyInfo class contains

```
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]

```

When I start the webjob, I ONLY configure the timer triggers if I'm running the webjob on the production slot:

```
            if (WebjobsCommon.InProductionMode)
            {
                Console.WriteLine("In production mode - turning on the TimerTrigger functions");
                configuration.UseTimers();
            }
```

Finally, my latest deployment makes use of the `IsPastDue` property to detect and stop multiple triggers firing:

```

            if (timerInfo.IsPastDue)
            {
                log.WriteLine("We're processing a past scheduled timer trigger, which we don't care about");
                return;
            }
```

... but it still fires twice in succession.

I guess I need to get the verbose logging turned on next and see if that tells me more?

**Comment by mathewc** [comment]
Can you share your site name via email? My GH user name @microsoft.com.

**Comment by mathewc** [comment]
From investigation of the logs in your production and staging slot, what is happening is that you actually have the **jobs running in BOTH slots** which accounts for the double invocations. Since your slots are configured with different storage accounts, the slots aren't sharing a [singleton lock](https://github.com/Azure/azure-webjobs-sdk-extensions/wiki/TimerTrigger), so your timer functions are running concurrently in both slots.

So you either need to fix your "IsProduction" logic (e.g. by making the relevant app setting a slot setting), or perhaps by stopping the jobs completely in your staging slot.
