### ISSUE TITLE
Getting lots of "Unable to aquire Singleton lock" during  localhost development

### ISSUE THREAD

**Issue by PureKrome** [Azure/azure-webjobs-sdk-extensions#25]
Heya :)

So I've just started playing around / trying to use the `TimerTrigger` with a new webjob. I'm doing localhost development to make sure the code works, before I deploy it up to Azure.

To do this, I click `F5` to `Debug` my webjob console app. Ok, great! works/etc... I then stop this (or the code throws an exception and crashes).

I then change one tiny thing and then hit `F5` again .. and then get this:

![image](https://cloud.githubusercontent.com/assets/899878/11802171/a8c6a47a-a341-11e5-975e-be76b2695a4f.png)

Sometimes, I wait 10 or even 20 seconds after the webjob stopped/stops and _then_ hit `F5` and still get that error.

Shouldn't the host 100% tear down after it's stopped? I should be able to hit `F5`, then close app, then hit `F5` straight away, right?

#Update / More info.

Here's my `program.cs` as a reference:

```
    class Program
    {
        // Please set the following connection strings in app.config for this WebJob to run:
        // AzureWebJobsDashboard and AzureWebJobsStorage
        static void Main()
        {
            var config = new JobHostConfiguration();
            config.Tracing.ConsoleLevel = TraceLevel.Verbose;

            config.UseTimers();

            var host = new JobHost(config);
            host.RunAndBlock();

            //var host = new JobHost();
            //// The following code ensures that the WebJob will be running continuously
            //host.RunAndBlock();
        }
    }
```

**Comment by mathewc** [comment]
When the listener starts for a particular TimerTrigger function, a blob lease (the Singleton Lock) is taken for a default time of 30 seconds. If you kill your console app, that lease will still be held until it expires naturally. You can control the default lease time via `JobHostConfiguration.Singleton.ListenerLockPeriod`. Take a look at how the extensions sample app handles this for speedy local debugging [here](https://github.com/Azure/azure-webjobs-sdk-extensions/blob/master/src/ExtensionsSample/Program.cs#L68). It handles local Console close events to do graceful shutdown.

Note that this is really only an issue when running locally. In Azure, if the JobHost shuts down (e.g role restarts, etc.) graceful shutdown logic will release the lock immediately so when the host starts back up it can be reacquired. If the instance does terminate abruptly w/o allowing the graceful shutdown logic to complete, then the natural lease timeout will still be in play. You can adjust that via the ListenerLockPeriod setting mentioned above, if you desire a shorter lease.

It's all about the right balance for production apps. With a shorter lease, there are more lease renewals required, which is why the default of 30 seconds was chosen. The listener then only needs to renew the lease every 15 seconds or so, reducing storage calls. Also note that if on JobHost startup the lease cannot be acquired immediately, the host will continue to try periodically behind the scenes. You should see in the Console logs that the lock is eventually acquired and the function starts running.

**Comment by PureKrome** [comment]
Ok wow. that's a lot to grok for a first pass at webjobs. Lets try and step back a tick to understand this.

> a blob lease (the Singleton Lock) is taken for a default time of 30 seconds.

So the webjob host (localhost _and_ production on azure) use BLOB storage to control some of the host's life-management? Is this related to: `AzureWebJobsStorage` app settings key?

>You can control the default lease time via JobHostConfiguration.Singleton.ListenerLockPeriod. Take a look at how the extensions sample app handles this for speedy local debugging here. It handles local Console close events to do graceful shutdown.

Okay - sweet. So for localhost, this could be dropped to a few seconds. If i'm hitting my local storage a fair bit, who cares? it's local only and it's when the console is running while i'm debugging....

If that's the case .. maybe it might be nice to make this _very discoverable_.

For example (using the _default_ code template)...

```
// To learn more about Microsoft Azure WebJobs SDK, please see http://go.microsoft.com/fwlink/?LinkID=320976
class Program
{
    // Please set the following connection strings in app.config for this WebJob to run:
    // AzureWebJobsDashboard and AzureWebJobsStorage
    static void Main()
    {
        // <MY SUGGESTION HERE:>
        // <First, some quick context>
        // <Second, the tip/trick and some code>
        // To help maintain the host's management, the web job uses an Azure BLOB storage
        //  to persist specific information. The web job polls this information every 30 seconds, locking access to the <something>.
        //  This is great for production, but annoying for localhost development. As such, reduce the time
        // when doing development to a few seconds. Need more info? http://blahblahblah..
        // For localhost development, reduce the time the Singleton is locked.
        // The-special-code-here-to-reduce-the-time

        var host = new JobHost();
        // The following code ensures that the WebJob will be running continuously
        host.RunAndBlock();
    }
}
```

**Comment by mathewc** [comment]
Yes - there is are some sophisticated mechanics being used behind the scenes to make scheduled functions run Singleton. The intent is for users to not have to worry about any of that of course. This Singleton Lock is only used when someone is using TimerTrigger. So I don't think we'd add that to the default template.

I have also considered changing it so that when running locally, a lock is not taken. While that would solve this issue for local testing, it would also mean that if you also have the same function deployed and running in Azure, you could have multiple instances executing concurrently, which would be confusing/problematic.

**Comment by PureKrome** [comment]
Hmm. No probs about _not_ adding anything to the default template. that makes sense - this is `TimerTrigger` specific.

I feel like there needs to be some easier discoverability about this. I'm not sure how, though :(

**Comment by mathewc** [comment]
The intent is for you NOT to have to discover anything about these low level details. It should just work for people. If the default lease period were 15 seconds (it was originally at one time), then you wouldn't be noticing this at all really, but it was changed to 30 seconds because that is what is best for deployed apps.

I'm open to making adjustments to this based on your feedback. We have lots of people using TimerTrigger, and your the first to question this. However if you ran into it, likely some others have as well.

One option would be for the SDK to use a lower default lease period when running locally. If you don't have any deployed functions also running, then this would work well. However if you did, those hosts would be using the 30 seconds, so you'd see the lease still being held as you do now. However, this would work well for the "getting started" case where a person is only running locally at the time.

**Comment by PureKrome** [comment]
>The intent is for you NOT to have to discover anything about these low level details. It should just work for people

I'm all for that :) Was just thinking about options, but yes! all for that :)

>One option would be for the SDK to use a lower default lease period when running locally
This I really like. But .. how do you define 'locally' ? via the connection string? 

e.g.: `<Setting name="AzureConnectionString" value="UseDevelopmentStorage=true" />`

>However, this would work well for the "getting started" case where a person is only running locally at the time.
That's the use case I'm mainly targetting in this issue - so yep :)

**Comment by mathewc** [comment]
For now, here's an approach that should work for you ([code here](https://github.com/Azure/azure-webjobs-sdk-extensions/blob/master/src/ExtensionsSample/Program.cs#L61)). Basically when running locally (based on your own environment variable) you can configure the lock period and other things.

**Comment by PureKrome** [comment]
Kewl. that reads, fine.

Q1. Do you think this could/will be baked in to the product/nuget-package at some time?

Q2. what does this [section of code](https://github.com/Azure/azure-webjobs-sdk-extensions/blob/master/src/ExtensionsSample/Program.cs#L76)  do? Why is it required for localhost dev? 

```
if (string.IsNullOrEmpty(filesConfig.RootPath))
{
    // when running locally, set this to a valid directory
    filesConfig.RootPath = @"c:\temp\files";
}
```

**Comment by mathewc** [comment]
Not sure yet about project template updates. Singleton lock and TimerTrigger are pretty new, so we'll want to continue to get feedback. Definitely once we arrive at the recommended best practices, we'll look into updating templates.

The second bit of filesConfig code you won't need. That's only needed in that sample because it is using FileTrigger - it's FileTrigger specific.

**Comment by PureKrome** [comment]
>Not sure yet about project template updates.

I didn't really mean the project templates. I ment the actual webjobs nuget library. I really like your concept of how we shouldn't need to discover anything. :sparkles: should just happen.

But right now, I have no way of knowing that I need to define these three lines:

```
config.Tracing.ConsoleLevel = TraceLevel.Verbose;
config.Singleton.ListenerLockPeriod = TimeSpan.FromSeconds(15);
config.Queues.MaxPollingInterval = TimeSpan.FromSeconds(2);
```

I'm just worried that other people might not know this too. So if this was maybe baked in .. sorta like what's going on with ASP.NET 5. Here's some sample code [from their docs](https://docs.asp.net/en/latest/conceptual-overview/aspnet.html#configuration) ...

```
if (env.IsDevelopment())
{
    // For more details on using the user secret store see http://go.microsoft.com/fwlink/?LinkID=532709
    builder.AddUserSecrets();
}
```

so maybe something like ...

```
if (host.IsDevelopment())
{
    // For more details on using the time based triggers see http://go.microsoft.com/fwlink/?LinkID=696969696969
    builder.UseDeveloperTimerSettings()
}
```

and of course, that method can accept optional values, with the defaults being set at 15secs and 2secs (for example).

>The second bit of filesConfig code you won't need. That's only needed in that sample because it is using FileTrigger - it's FileTrigger specific.

AH! gotcha.

**Comment by mathewc** [comment]
You don't *have* to set those - you might have more/less things that you want to configure when running locally. However, since there is a set of them that will be common (like these), I like your idea of adding a helper function that you can call to set up the usual defaults. We'll discuss this in our next team meeting :)

**Comment by PureKrome** [comment]
>You don't *have* to set those 

correct. but if i don't, the _developer_ experience is more painful. (eg. 30 sec lock).

>I like your idea of adding a helper function that you can call to set up the usual defaults. 

Yep! that's the idea. A simple _option_ for those that are doing dev. Just like what ASP.NET are offering (IMO).

>We'll discuss this in our next team meeting :)
![](https://31.media.tumblr.com/43e63461d1e3f22a49b18dbf15227a1d/tumblr_inline_n3t10oQfIh1solpjm.gif)

Mental note: I need to find a new cheering gif... i'm overusing this, now :(

**Comment by mathewc** [comment]
Ok, I've added `JobHostConfiguration.IsDevelopment` and `JobHostConfiguration.UseDevelopmentSettings()`. You can see an example in the extensions [sample here](https://github.com/Azure/azure-webjobs-sdk-extensions/blob/master/src/ExtensionsSample/Program.cs#L25). This new method sets up all the optimal local dev settings as mentioned above.

See the xml doc on these new methods for details. Basically if your environment has a setting **AzureWebJobsEnv**, IsDevelopment will be true. Note that these changes are in prerelease packages [available on myget](https://github.com/Azure/azure-webjobs-sdk/wiki/%22Nightly%22-Builds).

**Comment by PureKrome** [comment]
Thanks heaps for adding this :) Much appreciated, team :balloon:

**Comment by MegoCs** [comment]
@mathewc,
recalling this issue. i am having an issue related to that when i delete the triggerd webjob from the portal. it deletes the files associated with it. but keeps the job it self running and i can see it under the running processes in Kudu.
that cause the local version it say unable to get a singleton lock. so i had to manually kill the process of the deleted job.
![image](https://user-images.githubusercontent.com/14217594/61297146-e4370c00-a7db-11e9-9696-5ca72a9ef50f.png)

![image](https://user-images.githubusercontent.com/14217594/61297250-206a6c80-a7dc-11e9-9e41-a7708e1a9b8d.png)
