### ISSUE TITLE
FileTrigger does not support Renamed, Deleted WatcherChangeTypes

### ISSUE THREAD

**Issue by jakirkpa** [Azure/azure-webjobs-sdk-extensions#250]
Please provide a succinct description of the issue.

#### Repro steps

Provide the steps required to reproduce the problem

1. Set FileTrigger to use WatcherChangeTypes.Renamed or WatcherChangeTypes.Deleted
2. View WebJob log stated only Changed or Created are supported.

#### Expected behavior

Renamed and Deleted WatcherChangeTypes should be supported, and work fine externally to FileTrigger.

#### Actual behavior

WebJob will not start and log states only Changed and Created are supported.

#### Known workarounds

Write custom FileSystemWatcher and not use SDK.

#### Related information 

Provide any related information 

* Package version
* Links to source:  https://github.com/Azure/azure-webjobs-sdk-extensions/blob/master/src/WebJobs.Extensions/Extensions/Files/Listener/FileListener.cs  Lines 171-178

**Comment by christopheranderson** [comment]
Thanks for the feature request. These are intentionally blocked for now.

@mathewc - why did we implement these the first time around? Was there any weird things?

**Comment by robertmclaws** [comment]
Bubbling this back up because I ran into it today. Also, the `FileListener` is improperly testing for `WatcherChangeTypes` Flags it does not support. This should throw an exception, but does not:
```
public void ProcessQueue(
    [FileTrigger(@"queue\{name}", "*.json", WatcherChangeTypes.Created | WatcherChangeTypes.Renamed, true)] string messageEnvelopeJson, ILogger logger)
```

I'm going to fix this and submit a PR, as it is currently blocking my SimpleMessageBus project from working properly over network shares. 

The `Created` event fires before the file is finished writing, so the `FileTrigger` errors out because the file is still locked while packets are still going over the network connection. I wanted to get around this by:
   - testing for a network path
   - calling `File.WriteAllText()` to a temp file
   - calling `File.Move()` when it's done.

But that didn't work AND it didn't throw an error saying why... the renamed file just sat there.
