### ISSUE TITLE
DocumentDB output binding with async keyword

### ISSUE THREAD

**Issue by Yvand** [Azure/azure-webjobs-sdk-extensions#299]
I'm trying to create a TimerTrigger function that needs the async keyword.
Because of that I need to remove the out keyword on my DocumentDB attribute.
If I do that I get the following error:
```
"Microsoft.Azure.WebJobs.Extensions.DocumentDB: 'Id' is required when binding to a JObject property."
```
According to [DocumentDBAttribute.cs](https://github.com/Azure/azure-webjobs-sdk-extensions/blob/master/src/WebJobs.Extensions.DocumentDB/DocumentDBAttribute.cs) Id is required only for input bindings, so I understand that my binding is considered as an input binding, while I want it to be an output binding.
If I set an id, I have no error but document is not written in CosmosDB.

How can I have my output binding in an async function?

Here is the definition of my function:
```C#
public static async Task Run([TimerTrigger("0 */5 * * * *")]TimerInfo myTimer,
   TraceWriter log,
   [DocumentDB("ldapcpStats-db", "ldapcpStats-coll", ConnectionStringSetting = "AzureWebJobsDocumentDBConnectionString", PartitionKey = "DateTimeCreatedMMYY")] JObject ldapcpStatsDocument)
{
}
```

Thanks for your help

**Comment by paulbatum** [comment]
Hi there, I know this issue is quite old, apologies for missing it.

When you switch your function over to being async, you need to remove the out parameters (because C# requires this), and usually this means you need to change the type signature. So for example, instead of having an `out JObject foo` that you do `foo = myoutput` in your code, you switch to using `ICollector<JObject> foo` and then you call `foo.Add(myoutput)`. This post has some more information: https://stackoverflow.com/questions/46123181/why-do-i-need-to-add-an-out-parameter-to-my-output-bindings/46125511#46125511

So it is expected that no document is written when you remove the `out` keyword but do not make the change discussed above.

As for the id property - I am fairly sure you need this for output too, but it will need to be part of your JObject.

**Comment by Yvand** [comment]
Thank you for your answer, indeed this post helped me a lot to understand the issue and fix it.
