### ISSUE TITLE
Update SendGrid dependency to 6.3 or higher

### ISSUE THREAD

**Issue by rustd** [Azure/azure-webjobs-sdk-extensions#34]
Please see this thread for details: https://github.com/sendgrid/sendgrid-csharp/issues/176

**Comment by mathewc** [comment]
Moved to version 6.3.4, and also updated our package dependency.

**Comment by tbertenshaw** [comment]
I've just updated the webjobs libraries to 2.0.0-beta1  if i let the sendgrid library update to v8 rather than 6.3.4 then i get the error mentioned here https://github.com/sendgrid/sendgrid-csharp/issues/176  If i leave the sendgrid library as 6.3.4 i now get a "webjobs error indexing method" where i didnt before, 

Whats the correct version of sendgrid to use?, and what are the breaking changes on the sendgrid extensions which would cause the indexing method error?

**Comment by mathewc** [comment]
We've recently moved to the latest v8 version and updated all our SendGrid samples to that version. Those package versions are available on our myget feed. E.g. version **2.0.0-beta1-10369**.

**Comment by tbertenshaw** [comment]
yeah I've just updated to 2.0.0-beta1 from the public nuget feed. I get an exception when my webjob runs. 

```
System.IO.FileNotFoundException occurred
  FileName=SendGridMail, Version=6.3.4.0, Culture=neutral, PublicKeyToken=4f047e93159395ca
  FusionLog==== Pre-bind state information ===
LOG: DisplayName = SendGridMail, Version=6.3.4.0, Culture=neutral, PublicKeyToken=4f047e93159395ca
```

if i examine the Webjobsextension you can see its referencing the 6.3.4 dll.
![image](https://cloud.githubusercontent.com/assets/2010002/19416451/b29ddf62-9388-11e6-9beb-05c86a37d8a7.png)

**Comment by tbertenshaw** [comment]
I want to use public nuget feeds if possible. So should i revert to 6.3.4?

**Comment by mathewc** [comment]
Yes, you need to use 6.3.4 if you want to stay on the public nuget version. During that release where we moved to 6.3.4, there were also a few minor breaking changes. Likely the issue for you is that we've changed the required method signature so you use an `out` parameter, e.g. `out SendGridMessage`. See [this](https://github.com/Azure/azure-webjobs-sdk-extensions/pull/113) PR for details.

**Comment by tbertenshaw** [comment]
Thanks, 
     using out means that the method cannot be async i believe?

Any rough timeframe for the next version being on the public nuget?

**Comment by mathewc** [comment]
If you want your method to be async, bind to `IAsyncCollector<SendGridMessage>`. No date yet for next version - before the end of the year most likely. Team is all heads down right now on Azure Functions, which builds on all these repos.

**Comment by tbertenshaw** [comment]
can i await inside a method which doesn't have async in the signature?

**Comment by mathewc** [comment]
No - to use the `await` the method has to be declared `async`.

**Comment by tbertenshaw** [comment]
yeah thought so. Shame as i made all the calling functions awaitable.

 So presumably this is just a limitation with the Sendgrid extensions rather than being a webjobs limitation. 

So if i needed to perform some await-able logic before "sendgrid-ing" the results then i could either have two queue functions one which is await-able and drops an json object into another Queue for a sendgrid queue function to action upon, or i could process all the logic and emailing inside the same function but roll my own Sendgrid instantiation. (ifthat makes sense)

Cheers
Tim

**Comment by mathewc** [comment]
I don't understand your issue - if you want your function to be asyc, declare it async, await your report generation, then send one or more messages using a parameter bound to `IAsyncCollector<SendGridMessage>`, i.e. `await collector.AddAsync(message)`. If this still isn't clear, please share some code, or create a new issue.

**Comment by tbertenshaw** [comment]
@mathewc Sorry, after looking at the example with 

```
public static void ProcessOrder_JObjectAsyncCollector(
            [QueueTrigger(@"samples-orders")] Order order,
            [SendGrid] IAsyncCollector<JObject> messages)
        {
```
I assumed that it since it didn't have an `async` modifier that you either used async or used IAsyncCollector. I can see what you mean now,

**Comment by mathewc** [comment]
The sample code you shared was actually incorrect! :( I just pushed a fix. It should have read:

```csharp
public static async Task ProcessOrder_JObjectAsyncCollector(
    [QueueTrigger(@"samples-orders")] Order order,
    [SendGrid] IAsyncCollector<JObject> messages)
{
    JObject message = JObject.Parse(GetEmailJson(order));
    await messages.AddAsync(message);
}
```

**Comment by tbertenshaw** [comment]
Cool that makes more sense now :)
