### ISSUE TITLE
Guidance in using NotificationHub attribute in a locally-developed, precompiled, async Azure Function

### ISSUE THREAD

**Issue by pingzing** [Azure/azure-webjobs-sdk-extensions#347]
Hi! I'm attempting to create a Precompiled Azure Function that makes use of an Azure Notification Hub, and I'm having some difficulty getting to to run. I'm not certain if this is the place to go, but it seemed liked a good place to start =)

My issue is outlined below.

#### Repro steps
1. Start local development of an Azure Function in Visual Studio.
2. Create an async Function that uses the NotificationHub attribute. For example, here's a simplified version of mine:

```C#
[FunctionName("MyFunction")]
        public static async Task Run([TimerTrigger("0 */5 * * * *")]TimerInfo myTimer, 
                                     [NotificationHub]IAsyncCollector<Notification> notification,
                                     TraceWriter log)
        {                                    
            using (var httpClient = new HttpClient())
            {
                try
                {
                    // Make several async calls, and create a Windows TileNotification here...
                        await notification.AddAsync(new WindowsNotification(tileContent.GetContent()));
                    }                    
                }                
                catch (Exception ex)
                {
                    // log failure, etc.
                }
            }
        }
```
3. Observe the following error message when attempting to run locally:

```
Microsoft.Azure.WebJobs.Host: Error indexing method 'MyFunction.Run'. 

Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'notification' to type IAsyncCollector`1. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. ServiceBus, 
Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. config.UseServiceBus(), config.UseTimers(), etc.).
```

#### Expected behavior

I receive an error message with more specific information. The documentation for precompiled Functions using the NotificationHub attribute has plenty of examples of using an `out` binding to return a notification, but none in an asynchronous context. As such, I'm not totally sure what this error message is telling me--am I using IAsyncCollector incorrectly? Do I need to configure the NotificationHub attribute before I can use it? If so, are there required parameters? etc.

#### Actual behavior

A frustratingly-general error message is given =)

#### Related information 

Packages installed, according to NuGet in VS:
 * Microsoft.Azure.NotificationHubs 1.0.9
 * Microsoft.Azure.WebJobs.Extensions.NotificationHubs 1.0.0
 * Microsoft.NET.Sdk.Functions v.1.0.7
 * Microsoft.Toolkit.Uwp.Notifications 2.1.0 (for generating Tile notification payload)
 * NETStandard.Library v.2.0.0
 * Newtonsoft.Json v 10.0.3

**Comment by brettsam** [comment]
@pragnagopa -- can you help debug this issue?

**Comment by pingzing** [comment]
I ultimately ended up solving this--it turned out to be an issue with what I _think_ was an out-of-date version of the Azure Functions tooling installed with Visual Studio. Updating it seems to have fixed the issue.

**Comment by ErikAndreas** [comment]
@pingzing how did you solve this (in detail)? In addition to what you're describing I get compile warnings:

warning NU1602: Microsoft.Azure.NotificationHubs 1.0.7 does not provide an inclusive lower bound for dependency Microsoft.WindowsAzure.ConfigurationManager. An approximate best match of Microsoft.WindowsAzure.ConfigurationManager 1.7.0 was resolved.
 warning NU1701: Package 'Microsoft.Azure.WebJobs.Extensions.NotificationHubs 1.3.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.

runtime error:
Error indexing method 'nnn'
[2019-06-04 13:36:44] Microsoft.Azure.WebJobs.Host: Error indexing method 'nnn'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'notification' to type IAsyncCollector`1. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).

Azure Functions Core Tools (2.5.553 Commit hash: b63f2d6f5479718ca276f7b585a8cc6b9bc57c4f)
Function Runtime Version: 2.0.12382.0

**Comment by ErikAndreas** [comment]
ah, it's not supported for 2.x https://github.com/Azure/azure-webjobs-sdk-extensions/issues/239

**Comment by pingzing** [comment]
I think I must have been on functions 1.x, so I could take advantage of the output binding, yeah.

Also, going to close this issue, as it's definitely no longer relevant.
