### ISSUE TITLE
Allow for CosmosDB to set preferred read location for better perf

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-webjobs-sdk-extensions#363]
Per [this uservoice item](https://feedback.azure.com/forums/355860-azure-functions/suggestions/32759485-support-setting-preferred-location-preferences-on) which references [this document](https://docs.microsoft.com/en-us/azure/cosmos-db/tutorial-global-distribution-sql-api#net-sdk) sounds like we may get better read perf if allowed configuration of the location to read from in CosmosDB.  Not sure what impact is or if feasible but wanted to bubble up for tracking and triage.

/cc @ealsur

**Comment by ealsur** [comment]
We could implement this for the input binding, not sure which would be the time constraint to push this for the next version, what do you think @brettsam ?

**Comment by brettsam** [comment]
We'd need to think through the design. Right now we create a new DocumentClient for every unique URL we get. So having this be a per-function config option would be odd (which one would win?) We could have it be a global setting -- so every DocumentClient uses the same values and you set it up in host.json.

@ealsur do you want to try to figure it out? Any idea what the perf increase is?

**Comment by ealsur** [comment]
The perf increase depends really on the Location of the Functions App and the Location of the Cosmos DB regions.

The SDK will try to connect to the Write Region by default, if the Function App is in the same region as the Cosmos DB's Write Region, there is no perf improvement.
This comes in handy if the Function App is in one of the Cosmos DB's Read Regions. Instead of connecting to the Write region, it will (if the user sets the configuration) connect to the Read Region (it's closer) so read latencies will be lower.

I agree, since this is a global setting, it should go to `host.json`. Is this file also available in Consumption Plan @brettsam ?

**Comment by ealsur** [comment]
@jeffhollan I think the uservoice can be replied now that the requisite was merged?

**Comment by jeffhollan** [comment]
Yes I can do that - do you have documentation on the `host.json` config so I can make sure we document as well?  Here's what I have for the cosmosDB extensions config now:

```json
  "extensions": {
        "cosmosDB": {
            "connectionMode": "Gateway",
            "protocol": "Https",
            "leaseOptions": {
                "leasePrefix": "prefix1"
            }
        },
```
