### ISSUE TITLE
CosmosDbTrigger Continuation Token Increments on Exception

### ISSUE THREAD

**Issue by davetheunissen** [Azure/azure-webjobs-sdk-extensions#412]
Hi CosmosDbTrigger team, I can't seem to find any documentation on how the CosmosDb trigger modifies the lease collection.

The scenario I have is if the function being invoked throws an exception, I don't see a mechanism to 'replay' the trigger from the same continuation point. The continuation token in the lease collection increments regardless of how the function performs. 

Is the recommended pattern here to throw the failed documents into some sort of poison queue? I am essentially looking to implement hot backup functionality to some external storage. Should I be looking to use the Change Feed SDK instead in this scenario?

Appreciate any help or direction on this.

Thanks.

**Comment by davetheunissen** [comment]
Just found this stackoverflow question
https://stackoverflow.com/questions/48781419/how-to-re-trigger-cosmosdbtrigger-events-in-azure-cosmos-db-or-get-triggered-eve

Will close this issue.
Thanks

**Comment by ealsur** [comment]
Right now the closest thing is a PR that will enable you to configure retries: https://github.com/Azure/azure-webjobs-sdk-extensions/pull/349

There is a good article by Jeff pointing at stream processing with Event Hubs that also applies to the Cosmos DB Trigger, since both work similarly: https://hackernoon.com/reliable-event-processing-in-azure-functions-37054dc2d0fc

**Comment by davetheunissen** [comment]
Thanks very much Matias. I will dive into event hubs and take a closer look at that pattern. Appreciate you taking the time to review my question.
