### ISSUE TITLE
[Timer Trigger] Allow for multiple "named" triggers

### ISSUE THREAD

**Issue by cjrosa** [Azure/azure-webjobs-sdk-extensions#428]
Provide the ability to augment the timerName so that multiple timers, sharing the same blob storage account, can fire independently.  This becomes an issue within the ServiceFabric where multiple partitions of a Stateful Service each need their own timer, since each instance IS the same code.  The `TimerTriggerAttribute `could have a TimerNamePrefix/Postfix that could be used to make each instance's timerName unique.  I believe most of the code is in the TimerBindingProvider.cs class where it currently assumes the $`"{AssemblyName}.{MethodName}"`.  The mechanism should support `INameResolver `so Pre/Post fix values can be contextualized appropriately.

**Comment by mathewc** [comment]
The isolation scoping for TimerTrigger (and other host internal logs) is based on HostId, which by default is derived from the full assembly name of your job assembly. The singleton locks taken on startup for the timer function listener are scoped to HostId, so the same timer function only runs on one of the N scaled out instances.

So if you want to scope instead per partition (or whatever level you decide), you can on startup assign each host a unique HostId. Are you using v2 or v3 of the SDK/Extensions? Each allows you to set a HostId on host startup.

HostIds should be static/durable - i.e. you wouldn't want to generate new HostIds when hosts start up. But if you have a static set of IDs for your deployment, you can assign each host one of them.

**Comment by cjrosa** [comment]
Thank you for the response!  We're using V3 and the I suspect the each partition's ID would work.  That said, we've adjusted our approach since, buy created a Singleton service which hosts the WebJob TimerTrigger.  This works better [for us] as it provides an opportunity coordinate ALL activities as opposed to  each partition's timer firing independently, without knowledge of the specifics of each other.

**Comment by acds** [comment]
Hi!

To confirm, does .UseHostId just apply to the schedule or also the the Singleton Lock ?

In the scenarios that the same WebJob implementation is deployed to multiple App Services - for each of our environments.

A number of the environment happen to use the same storage account - we have reasons.

However each WebJob Trigged Function (per App Service) performs activity specific to that App Service so should and can run concurrently with no impact.

If one configures the .UseHostId with something durable to each App Service, this will then partition by App Service ?

Otherwise, assuming a similar schedule for each environment, the Trigged task, will block until it's able to acquire, in turn, the singleton blob lease - subject to the default (or otherwise configured) WebJob timeout ?

Thanks!
