### ISSUE TITLE
Prevent running past-due jobs with timer

### ISSUE THREAD

**Issue by BrianVallelunga** [Azure/azure-webjobs-sdk-extensions#43]
While I can check if a timer is past due during execution, it would be better if I could disable this feature in the TimerTrigger attribute itself. I'm thinking:

    public static void MyJob([TimerTrigger("0 0 */2 * * *", RunWhenPastDue = false)] TimerInfo timerInfo)

I'm not exactly sure what the property should be called, but being able to set it to false would be helpful. It would also be helpful if it didn't seem to have so many false positive runs: https://github.com/Azure/azure-webjobs-sdk-extensions/issues/40

**Comment by mathewc** [comment]
You can already do this via `[TimerTrigger("0 0 */2 * * *", UseMonitor = false)` which will disable schedule tracking/monitoring. However, I believe you want to do this because of issue https://github.com/Azure/azure-webjobs-sdk-extensions/issues/40 which we need to get to the bottom of. In the other issue I point to an updated prerelease build that has bug fixes that may fix this - can you try that? Hopefully we can get a repro together for this issue and get it fixed, rather than you having to disable the feature :)

**Comment by BrianVallelunga** [comment]
Thanks for the info. Hopefully they'll just get more reliable with the latest fixes.
