### ISSUE TITLE
CosmosDB Input Binding: Document Client Input - First Request Latency

### ISSUE THREAD

**Issue by mayoatbm** [Azure/azure-webjobs-sdk-extensions#440]
The first request to Cosmos DB using a document client from the CosmosDB trigger is always slow.  The [CosmosDB docs](https://docs.microsoft.com/en-us/azure/cosmos-db/performance-tips) mention this first request latency and a workaround (call OpenAsync) but it doesn't seem to be implemented in the trigger.

We can't do this initialization in the function itself as the document client is uninitialized each time the function runs and makes the function slow every time.

#### Repro steps

1. Create a function with a CosmosDB trigger accepting the document client as an input parameter

2. Make two calls with the document client, one after the other.

#### Expected behavior

Both calls are relatively fast based on RUs and other factors.

#### Actual behavior

The first call is very slow. The second call is very fast.

![slow first request](https://user-images.githubusercontent.com/29760620/42962528-ace02b7c-8b46-11e8-9c07-09b548e95f6e.png)

#### Related information 

* Function Runtime: 2.0.11888.0
* Invocation Id: 6840d3bb-76e4-48b7-9d76-6f013df07428
* Region: East US 2

PS. Thanks for all your hard work on these extensions. They're great.

**Comment by ealsur** [comment]
@mayoatbm The latency comes from the fact that the Trigger needs to initialize the state and connections to the source collection and leases collection.

If you run in Consumption Plan and your instances go idle (see the note in the [official docs](https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale#how-the-consumption-plan-works)) and you don't have any activity in ~10 minutes, the instances running the Trigger will be shut down. Any new change afterwards will require the Trigger to re-initialize the state. If your flow of changes is constant, then you won't run into this scenario, because Consumption Plan won't shut down the instances. 

An additional workaround is to create a simple Time Trigger function that runs every 5 minutes in the same Function App. The Time Trigger will keep the instance alive.

In App Service Mode, since the instance is always running, you don't run into this scenario.

**Comment by mayoatbm** [comment]
@ealsur  Thanks for looking into this.

The limits/behavior of the consumption plan make sense to me.

I think my main point is that this initialization (looks like the same thing OpenAsync does) should happen when the function app starts up (whether initially or from an idle state) and not during execution of the individual function inside the app. Since the trigger is providing the client, it is in the best position to do this at the right time. 

Does that help clarify what I think the issue is here?

**Comment by ealsur** [comment]
@mayoatbm What you are saying makes sense.

The initialization of the connections is not done on the triggering of the Function, it is done on the startup of the Host (Function App) that contains the Trigger. When there are new changes, there is just a small call to your own code only, no initialization happens (no OpenAsync either).

The [StartAsync](https://github.com/Azure/azure-webjobs-sdk-extensions/blob/dev/src/WebJobs.Extensions.CosmosDB/Trigger/CosmosDBTriggerListener.cs#L63) call happens when the Host initializes on all Function triggers, the Cosmos DB Triggers at that point, initializes all connections.

When the Function is triggered, there is [a handler](https://github.com/Azure/azure-webjobs-sdk-extensions/blob/dev/src/WebJobs.Extensions.CosmosDB/Trigger/CosmosDBTriggerObserver.cs#L41) that will send the changes to your code, there is no initialization logic there.

Is your code within the Function creating any other connections / clients to other services? Are you using any Output Binding?

**Comment by mayoatbm** [comment]
@ealsur   Thanks for clarifying what's happening behind the scenes. 

Another function in that app uses the IAsyncCollector output binding for CosmosDB. That one doesn't show any of this behavior (i guess because it only runs once?). There are no other connections/clients in the app (the other functions are http triggered).

I noticed this issue and obtained the screenshot above by using the dependency tracking functionality of app insights. The dependency tracking is just around the calls to cosmos (two sequential calls) and you can see that the first one is always way slower than the second (which led me to initialization logic). 

As a test, i created our own cosmos db client and initialized it on startup (using openasync) and both calls were sub 100ms (which kinda points to initialization logic).

**Comment by ealsur** [comment]
I see. In your screenshot, am I correct in assuming that EnrichDocumentAsync is the Function App and GetDocumentFromCosmos is the Function?

After you receive the the changes, are you calling any other client or saving the documents somewhere? Could it be some cold-start in that path?

**Comment by mayoatbm** [comment]
@ealsur 

EnrichDocumentAsync is the name of the individual function in the app. GetDocumentFromCosmos is just what i named the operation.

The overall scenario works like this:

1. Function A receives a batch of documents (length N) from Stream Analytics
2. Function A triggers orchestrator Function B (Durable functions) with the batch of documents
3. Function B triggers N instances of activity functions C to enrich each document (fan out)
4. Function B  receives the enriched documents (fan in) and triggers activity function D to save them all at once (via IAsyncCollector)


Function C is what makes the two calls in the screenshot to Cosmos DB.

Hope this helps.

**Comment by ealsur** [comment]
Thanks for the clarification, you are using Durable Functions then. I'm not familiar how Durable Functions orchestrates instances, it might be different from normal Functions flow.

What I don't understand is how the "Cosmos DB Trigger" fits in that flow. The Cosmos DB Trigger cannot receive documents from an orchestration, it cannot be directly invoked from another Function because it is listening to the monitored collection.

How is the signature of Function C?

**Comment by mayoatbm** [comment]
@ealsur 

Anytime. Yes, we are using durable functions. In general, the activity functions in durable functions work just like non durable ones (orchestrator functions are more quirky).  

I think this might be the source of confusion. We're not monitoring a collection in this scenario, we're using the form of the trigger where we accept  the document client as input.

![image](https://user-images.githubusercontent.com/29760620/43918621-63b73fc0-9bc8-11e8-9e04-9213024e820c.png)

**Comment by ealsur** [comment]
Ahhh ok, this is not a Cosmos DB Trigger 😄  If it's ok, I'll edit the title. That is a "Cosmos DB Input Binding" see [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-cosmosdb-v2#input).

This is different from the Trigger, please disregard my previous comments and flow, as they applied to the Trigger, not the Input Binding.

When you receive the  `DocumentClient`, you are receiving a singleton instance that is shared on all calls within the instance. But that singleton instance [does not call OpenAsync](https://github.com/Azure/azure-webjobs-sdk-extensions/blob/dev/src/WebJobs.Extensions.CosmosDB/Services/CosmosDBService.cs#L20) when is created. So yes, your first call ever in a given instance, will probably have the expected delay as explained.

Now, calling OpenAsync also has some drawbacks in accounts with a lot of collections, because it will try to initialize internal caches to all databases/collections. Making this a default behavior might not be a great idea as it depends on each case.

**Comment by mayoatbm** [comment]
@ealsur  

That's totally my bad, apologies for the confusion. Thank you for editing the title.

Yup, that matches up a lot better with the behavior we were seeing. I can understand not wanting to make this default behavior if there are other side effects. Is a toggle/flag a viable alternative?

**Comment by ealsur** [comment]
Sadly no, there is no configuration you can toggle. But an alternative would be to maintain your own `static` client instance, there is a sample [here](https://github.com/ealsur/serverless-recipes/blob/master/cosmosdbstaticclient/src/HttpTriggerToStaticClient.cs).

The effect is similar to the Cosmos DB Input Binding the way you are using it, but you can customize the DocumentClient init behavior, for example, call the OpenAsync when the static variable is created.

**Comment by mayoatbm** [comment]
@ealsur 

That's what we'll do then. Pulling in the static client looks straightforward. 

Thanks for all the help, and sorry again about the confusion.
