### ISSUE TITLE
Inbound WebHook uses publishing credentials?

### ISSUE THREAD

**Issue by pbolduc** [Azure/azure-webjobs-sdk-extensions#46]
I think I understand why you needed to do this, however, isn't it a security risk giving a third party credentials that can be used to deploy code to you web application?  If your publishing credentials are exposed, settings, such as storage accounts keys, application IDs, database connection strings could be exposed. With those credentials, can I log into the SCM portal? Deploy any code to the web site via WebDeploy?

Unless I dont understand something correctly, I would expect a large warning of the risks.  

The WebHooks SDK might be better choice?

**Comment by mathewc** [comment]
Thanks for raising - you are totally correct and we are aware of this. This issue is a duplicate of https://github.com/Azure/azure-webjobs-sdk-extensions/issues/36. I have added a bold note to the wiki.

We are working on a new model for WebHooks + WebJobs scenarios. You might want to check out what we're doing [here](https://github.com/Azure/azure-webjobs-sdk-script). That library also uses ASP.NET WebHooks under the covers. Here's an example of a [GitHub WebHook](https://github.com/Azure/azure-webjobs-sdk-script/tree/master/sample/WebHook-GitHub).
