### ISSUE TITLE
cannot use Microsoft.Azure.WebJobs.Extensions.CosmosDB NuGet from .Net Framework

### ISSUE THREAD

**Issue by willportnoy** [Azure/azure-webjobs-sdk-extensions#573]
NuGet Packages:

1. "Microsoft.Azure.WebJobs.Extensions.CosmosDB" depends on "Microsoft.Azure.DocumentDB.Core"
2. "Microsoft.Azure.DocumentDB.ChangeFeedProcessor" depends on "Microsoft.Azure.DocumentDB.Core" or "Microsoft.Azure.DocumentDB" depending on target framework.

When adding "Microsoft.Azure.WebJobs.Extensions.CosmosDB" to a .NET Framework Console application (much like you would for a web job), you will likely encounter this compilation error when using "Document":

error CS0433: The type 'Document' exists in both 'Microsoft.Azure.DocumentDB.Core, Version=2.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' and 'Microsoft.Azure.Documents.Client, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

#### Repro steps

Provide the steps required to reproduce the problem (I attached a reproduction).

1. Make .NET Framework console application
2. Add reference to NuGet package "Microsoft.Azure.WebJobs.Extensions.CosmosDB"
3. Try to use "Microsoft.Azure.Documents.Document" symbol.

#### Expected behavior

I should be able to use the CosmosDB from a .NET Framework web job.

#### Actual behavior

It doesn't work.

#### Known workarounds

1. It's possible you could use targetFramework in the packages.config but that doesn't work for PackageReference (https://github.com/Microsoft/dotnet/issues/860).
2. Perhaps "Microsoft.Azure.WebJobs.Extensions.CosmosDB" could follow the same patterns as "Microsoft.Azure.DocumentDB.ChangeFeedProcessor" with regard to "Microsoft.Azure.DocumentDB.Core" and "Microsoft.Azure.DocumentDB".
3. It would be nice if "Microsoft.Azure.DocumentDB.Core" and "Microsoft.Azure.DocumentDB" were packaged as a single NuGet with multiple target frameworks.

#### Related information 

[NoCosmosTrigger.zip](https://github.com/Azure/azure-webjobs-sdk-extensions/files/3306864/NoCosmosTrigger.zip)

**Comment by v-anvari** [comment]
Hi @willportnoy , as mentioned in [#715](https://github.com/Azure/azure-cosmos-dotnet-v2/issues/715#issuecomment-505180380), the v3 SDK targets .NET Standard to use [Microsoft.Azure.WebJobs.Extensions.CosmosDB](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.CosmosDB)

It's ideal to use [Microsoft.Azure.WebJobs.Extensions.DocumentDB](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.DocumentDB) for v1 since its dependencies are targeted to [.Net Framework](https://www.nuget.org/packages/Microsoft.Azure.DocumentDB/)

Please feel free to open the issue in case of any queries
