### ISSUE TITLE
Need support for integer in Cosmos DB binding

### ISSUE THREAD

**Issue by wisesimpson** [Azure/azure-webjobs-sdk-extensions#605]
Currently using `SELECT TOP {amount} * From c` in `sqlQuery` of Cosmos DB bindings will hit an error.
> The count value provided for a TOP clause must be an integer.

I think the cause is here: https://github.com/Azure/azure-webjobs-sdk-extensions/blob/7160d758c40551b5a283dbc24011ffa89c9ffa6b/src/WebJobs.Extensions.CosmosDB/CosmosDBSqlResolutionPolicy.cs#L49

Any parameter is assumed as a string, but `TOP` is expecting integer.

**Comment by v-anvari** [comment]
Hi @wisesimpson , Apologies for the delayed response. 

The amount seems to have {}. The query to be updated as "SELECT TOP 1000 c. ", Since the integer will be considered as string if {} applied.

Please find more information [here](https://docs.microsoft.com/en-us/azure/cosmos-db/sql-query-subquery).

**Comment by wisesimpson** [comment]
Hi @v-anvari Thanks for your reply, but it's Cosmos DB binding with a variable `amount`.
Can you show me what's the right way to write it with a variable?

**Comment by v-anvari** [comment]
Hi @wisesimpson , Have you tried any of these [sql-query-select#examples](https://docs.microsoft.com/en-us/azure/cosmos-db/sql-query-select#examples). Since, TOP expects only integers, please try to assign "amount" and return its values by calling it.

There are few GitHub[ examples here](https://github.com/Azure/azure-cosmos-dotnet-v3/tree/master/Microsoft.Azure.Cosmos.Samples/Usage)
