### ISSUE TITLE
Access to the http response object for returning a big result as stream

### ISSUE THREAD

**Issue by pablocastillaquintas** [Azure/azure-webjobs-sdk-extensions#606]
Hi!

Imagine you have an AzureFunction that will send back a lot of information through HTTP (gigas). I would love to have access to the response stream in order to inject the response into it and not having issues with the RAM.

Is there a way to do it? I can not find a Http output attribute.

Thanks

**Comment by v-anvari** [comment]
Hi @pablocastillaquintas , Apologies for the delayed response, the issue was somehow lost in between the stack. You can access the output by adding different output bindings - [Triggers and bindings](https://docs.microsoft.com/en-us/azure/azure-functions/functions-triggers-bindings?tabs=csharp).

If you talking about the Http Response class, then here are few docs: 
[Http Response Message](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpresponsemessage?view=net-5.0)
[Http Response](https://docs.microsoft.com/en-us/python/api/azure-functions/azure.functions.httpresponse?view=azure-python)

**Comment by v-anvari** [comment]
Closing this issue as there is no further activity, please feel free to reach back to us in case of any further queries related to this issue
