### ISSUE TITLE
TimerTrigger won't run when define day of week in ncrontab

### ISSUE THREAD

**Issue by EwertonJordao** [Azure/azure-webjobs-sdk-extensions#643]
Please provide a succinct description of the issue.

I try to use timer trigger with Twilio on PowerShell runtime, work fine, but when to try to use on azure functions specify a crontab "schedule": "* 0 12 * * MON,FRI" don't work in the second day, and after this don't work anymore. When I enter in function for seeing what's going on trigger start without start manual. I use a free tier to do this trigger.

#### Repro steps

Provide the steps required to reproduce the problem

1. Step A
{
  "bindings": [
    {
      "name": "Timer",
      "type": "timerTrigger",
      "direction": "in",
      "schedule": "* 0 12 * * MON,FRI"
    },
    {
      "type": "twilioSms",
      "name": "message",
      "accountSidSetting": "TwilioAccountSid",
      "authTokenSetting": "TwilioAuthToken",
      "from": "",
      "direction": "out"
    }
  ]
}
application setting 

"WEBSITE_TIME_ZONE":"E. South America Standard Time"

![image](https://user-images.githubusercontent.com/12378570/80871698-1ee33580-8c84-11ea-9711-eea9ebaa62a3.png)

#### Expected behavior

Provide a description of the expected behavior.

#### Actual behavior

Provide a description of the actual behavior observed. 

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Package version
v3 function 

* Links to source

**Comment by v-anvari** [comment]
Hi @EwertonJordao , There has been few fixes made on timer trigger lately, which should have fixed this issue by now. Let us know if you are still facing the issue with timer trigger.

If you are still facing the issue, let us know the "**Function App Name**", with the latest "**Time Stamp**", so that we can check the logs.

**Comment by EwertonJordao** [comment]
Hi @v-anvari, for me is the same experience, The function started when I check the code, but won't run time trigger configure, name of the function is __cfuntw__ and configuration is:
{
"bindings": [
{
"name": "Timer",
"type": "timerTrigger",
"direction": "in",
"schedule": "* 0 12 * * MON,FRI"
},
{
"type": "twilioSms",
"name": "message",
"accountSidSetting": "TwilioAccountSid",
"authTokenSetting": "TwilioAuthToken",
"from": "",
"direction": "out"
}
]
}
__Time zone__
![image](https://user-images.githubusercontent.com/12378570/95788529-17ec3480-0cb2-11eb-81ae-63f7ee268642.png)

Fired when I access the function :
![image](https://user-images.githubusercontent.com/12378570/95789212-77970f80-0cb3-11eb-8a61-1272bbff6fb7.png)

**Comment by v-anvari** [comment]
Hi @EwertonJordao , if you are checking the app the next day that is in 24 hr duration, then the crontab expression you have mentioned checks only on Monday and Friday, which in this case is wrong. 

If you are trying to run the function app Mon - Friday, then the [CronTab](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-timer?tabs=csharp) expression should be " 0 * 12 * * MON-FRI" , which means 12:mm:00 (12:00 PM)  on Monday to Friday of every month on all valid days, for more details on crontab please refer to [link](https://github.com/atifaziz/NCrontab). 

I have checked the logs, and they didn't show any expected error. Please try changing the expression and let us know if that helps.

**Comment by EwertonJordao** [comment]
Hi @v-anvari , No, In my case, I specify a ncrontab to run on Monday and Friday and exclude other days. 
![image](https://user-images.githubusercontent.com/12378570/96503103-2645cd80-1229-11eb-94d2-5b20fc4c0c4f.png)

I think my cron expression is ok. The Trigger is configured to run on my local timezone.

**Comment by v-anvari** [comment]
Hi @EwertonJordao , I was going through the logs from 2020-10-1 16:29 to 2020-10-20 16:14. I got to see that "Always On" is disabled. Since your function app is a dedicated plan, the function host might be getting idle due to inactivity, shared a screenshot below. 

![image](https://user-images.githubusercontent.com/66122429/97216692-37c04400-17ec-11eb-9ff6-34acef687750.png)

**Applens Log Report:** 
"We detected that you have unscheduled function execution(s) which is past due because of host start up".
**Recommended Action**
1. Function executions will be pastdue when the current function invocation is later than scheduled. For example, a function app restart might cause an invocation to be missed.
2. [Always On](https://docs.microsoft.com/en-us/azure/app-service/faq-availability-performance-application-issues#how-do-i-decrease-the-response-time-for-the-first-request-after-idle-time) - enable

**Kusto Logs:** 
_Run: GetFunctionsExecutionsList_ 
PreciseTimeStamp >= datetime(2020-10-1 16:25:00) and   PreciseTimeStamp <= datetime(2020-10-20 16:10:00)

**__Kusto Output :**_  (It has run only once in those days)._ 
"FunctionName": cfuntw,
"LastExecution":  2020-10-12T17:31:56.3992567-03:00,

@fabiocav, Any further suggestions on how to keep the function host running?

**Comment by EwertonJordao** [comment]
Ok, in this case, I need to change my service plan correctly? Move to a billed tier to enable Always On.

**Comment by v-anvari** [comment]
Yes let us know if that works, if not we can check the logs again for the latest runs.
