### ISSUE TITLE
For all the new extensions, rename ConnectionString attribute prop (and others)

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-extensions#67]
New extensions like ApiHub (Key), DocumentDB (ConnectionString), MobileTables (ApiKey), NotificationHub (ConnectionString) need to rename their attribute properties to make it clearer that these properties contain app setting names that point to the actual value.

The recommendation is to change "ConnectionString" to just "Connection" as in the script runtime.

**Comment by mathewc** [comment]
@brettsam @safihamid

**Comment by brettsam** [comment]
I'm not sure 'Connection' works for all 'key name' attributes. For example, MobileTables has both ApiKey and MobileTableUri that are lookup values. In reality, MobileTableUri doesn't really need to be stored in an app setting (since it's not a secret), but we eventually want a picker for it. ApiKey likely will not have a picker unless Mobile Apps makes it an official feature.

What if we suffixed all of these settings with 'Setting'?
ApiKey -> ApiKeySetting
MobileTableUri -> MobileTableUriSetting
ConnectionString -> ConnectionStringSetting

Thoughts?
