### ISSUE TITLE
CosmosDB trigger loses document if function app crashes

### ISSUE THREAD

**Issue by MartinWickman** [Azure/azure-webjobs-sdk-extensions#723]
If the function app crashes (is stopped/killed) during processing of a document/batch (using CosmosDB trigger change feed), the trigger will continue with the *next* document/batch once the app is up again, effectively losing that batch.

For mission critical operations, this is not really acceptable considering there just isn't a way to handle this situation.

#### Repro steps

1. Start a function with the cosmos trigger
2. Update a document in cosmos
3. End the function process (kill it) while it's processing the event
4. Start it again
5. Notice that it does not retry the same document again.

#### Expected behavior

The trigger should send the same document again until the function returns.

A good middle ground is making it work the way the Event Hub trigger handles it (Event Hub trigger retries the same event only if the app does not respond at all). 

Without knowing the details, it seems to me that the trigger should only update the checkpoint *after* the function has completed, not before (which it looks like to me). 

#### Actual behavior

The function does *not* receive the same document event again. Rather, the next document change is triggered. So the document change is lost.

#### Known workarounds

It seems if you add a retry policy like `[FixedDelayRetry]` to your function, the checkpoint is kept properly. This works if you `ctrl-C` the app at least.

#### Related information 

microsoft.azure.webjobs.extensions.cosmosdb\3.0.10

**Comment by CodeMonkey321** [comment]
You are wrong about the expected behavior. The documentation clearly states that it is at-most-once delivery.

Why this is the case is beyond me and makes the ChangeFeed Function trigger completely useless for 99% of workloads. Due to risk of data loss.

Writing a custom trigger is also not an option because it is not supported when hosting the Function Runtime in Azure.

But I agree that this should be changed or at least have it as an option between how it works now and how it works in the EventHub trigger where throwing an exception makes the trigger retry instead of just blindly checkpointing the progress.

I think your only solution is to run a webjob or web app using the ChangeFeedProcessorHost which is annoying to say the least.

**Comment by MartinWickman** [comment]
> The documentation clearly states that it is at-most-once delivery.

I couldn't really find that clearly stated that at-most-once is the way it works, and I doubt that's really the intention. Looking at [this doc](https://docs.microsoft.com/en-us/azure/cosmos-db/troubleshoot-changefeed-functions#some-changes-are-missing-in-my-trigger) it says:

> Note: The Azure Functions trigger for Cosmos DB, by default, won't retry a batch of changes if there was an *unhandled exception* during your code execution. 

That is expected, but if the behavior we're talking about is a *feature*, then it should loudly be stated in the docs that if your app crashes without returning for whatever reason, you'll lose any in-flight documents. 

Note that I understand the reasoning behind Event Hub trigger doesn't do retries because of poison messages and high cost (consumption), but that's not really the issue here.

**Comment by CodeMonkey321** [comment]
@MartinWickman you are right I remember it was written more clearly, and its really not, but it do say any unhandled exceptions, which I take to mean that user code let an exception bubble up to the host processor will not be handled, in this case its simply ignored.

If you see the trigger in the source code you will find a `TryExecute` method executing the user function. This method captures the exception and then swallows it so its never seen by the ChangeFeedProcessor, it just thinks everything is fine, checkpoints and then continue onward.

And I agree it should be a red flashing banner on every page that has CosmosDbTrigger mentioned that it is not robust and will introduce data loss if you rely upon it.

**Comment by ealsur** [comment]
The instance crashing and your code throwing an unhandled exceptions are potentially two different scenarios.

The order of events is the following:

1. Changes are read from the Change Feed from the Cosmos DB container
2. Changes are delivered to your Function
3. Once your Function completes execution (success or failure due to unhandled exception), checkpoint in the lease store the current batch identifier as completed.

If the instance crash happens while your code is running, it means that the order of events reached 2 but never reached 3, because the instance crashed and there is nothing running any kind of code. In that case, when a new instance is up again, the same batch would be retried because the previous one never checkpointed.

As for unhandled exceptions in your code, this follows the same design as other Event driven triggers, like Event Hub. As far as I know, the design choice was to avoid an infinite bill for Consumption Plan users in case the error was not transient but something that would cause a batch to retry forever. And for that reason there is the proposal to implement the Retry configuration for all Event based triggers: https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-error-pages?tabs=csharp#retry-policies-preview

**Comment by MartinWickman** [comment]
Yes, you are correct. I can no longer reproduce this behavior. Very odd. Maybe it was something with my setup or combination of libs and running the app locally with the CosmosDB emulator. For now, I'll close this report. Thanks and sorry for wasting your time.

**Comment by ealsur** [comment]
> Yes, you are correct. I can no longer reproduce this behavior. Very odd. Maybe it was something with my setup or combination of libs and running the app locally with the CosmosDB emulator. For now, I'll close this report. Thanks and sorry for wasting your time.

There is no time wasted if knowledge was gained 😄

**Comment by CodeMonkey321** [comment]
I'm honestly still confused.

So my best bet would be something like:
```
public async Task Run([CosmosDBTrigger()]IReadOnlyList<Document> input, ILogger log)
        {
            try
            {
                var timeout = DateTime.UtcNow.AddMinutes(5);
                while (true)
                {
                    try
                    {
                        var completedSuccessful = ImportantWork();
                        if (completedSuccessful)
                        {
                            return;
                        }                        

                        if(DateTime.UtcNow > timeout)
                            Environment.FailFast("Lets not lose data");
                        else
                            await Task.Delay(5000);
                    }
                    catch (Exception)
                    {
                        log.LogError("New Attempt");
                    }
                }
            }
            catch (Exception)
            {
                log.LogCritical("Data loss");
            }            
        }
```

**Comment by ealsur** [comment]
Normally the pattern I've seen applied with Event Processing involves using dead-letter queues. When you detect a message/event that would not be processed, you can:

1. Send them to a dead-letter queue for later analysis.
2. Send them to another place that would retry.

In your code, the LogCritical can very well do anything, it is not yet data loss because you have the list of documents right there. You can retry based on the nature of the error, log each document, save them in a queue/another collection with a retrying trigger/etc.

**Comment by CodeMonkey321** [comment]
> Normally the pattern I've seen applied with Event Processing involves using dead-letter queues. When you detect a message/event that would not be processed, you can:
> 
> 1. Send them to a dead-letter queue for later analysis.
> 2. Send them to another place that would retry.
> 
> In your code, the LogCritical can very well do anything, it is not yet data loss because you have the list of documents right there. You can retry based on the nature of the error, log each document, save them in a queue/another collection with a retrying trigger/etc.

@ealsur I would agree with you if the Event Processing was not backed by any medium. Say reading from a wire or something low level where data is lost if it is not read. But nothing is lost in Cosmos.

But for cases like ChangeFeed, EventHub and even Service Bus with the risk of running out of space on the queue/topic I would much rather simply be able to halt processing and continue when the delivery endpoint is up again or my code is fixed or whatever causes the issue. 

The case with CosmosDB is a little more complex as the ChangeFeed don't actually reflect point-in-time changes but is rather a ordered projection of the latest version of each entity and halting processing can make you miss intermediate updates, but that is always a risk with ChangeFeed. But that aside. 

Having to Dump data into a storage account or other service defeats the ease of use of the ChangeFeed and its ability to act as a buffer between components.

But thanks for the discussion, I respect that the Azure Functions team has a different opinion.

**Comment by ealsur** [comment]
@CodeMonkey321 

> But nothing is lost in Cosmos.

That is not 100% true as you can certainly delete a document, which would erase the history from the Change Feed. If I fail processing a batch of documents, and Functions had retries enabled, but something deletes the document inbetween, then the retry will no longer have that document on the batch. There are scenarios that due to the inherent nature of the Change Feed (like immediate updates missing) should be taken into consideration.

The Trigger is limited by the Change Feed behavior and basically just adds scalability (distribution of leases across instances dynamically) and simplicity (bookkeeping) but there are always things that need to be considered in the design.

I think the Functions design for retry configuration is a positive thing that will provide flexibility, I don't know when that will be released 100% or what's the plan there though.

Another topic you mentioned which makes sense is, how do you disable a Function when you detect an error that is not transient. As far as I understand, there are Management APIs for that but a Function cannot be disabled by itself's code, unless someone from the Functions team knows and can share how to. This scenario would be potentially the same when processing Event Hub for example.

**Comment by CodeMonkey321** [comment]
@ealsur your are right about Cosmos and deletes, I forget since we always use soft-delete with TTL when we need to record deletes in the ChangeFeed.

Having to call the management API just to disable a function, I think defeats the purpose of Functions and Triggers being easy and fast to develop and use. I'm not saying it can't be done but its a lot of hoops to go through for something that should be build in.

The Circuit breaker pattern is old and it should have been implemented into the Function runtime if you ask me, at least as a optional configuration. Now it seems the team that writes the Triggers have to balance protecting unwitting developers from runaway cost on consumption plans vs delivering resilient and easy to use features.

**Comment by ealsur** [comment]
> Having to call the management API just to disable a function, I think defeats the purpose of Functions and Triggers being easy and fast to develop and use. I'm not saying it can't be done but its a lot of hoops to go through for something that should be build in.

I agree, having a service wide guidance on how to handle a circuit breaker situation for any Trigger would be ideal. As you mention, as authors we need to leverage and balance consumption plan scenarios vs resiliency on event processing. Having these service wide Retry Configurations I believe are a step in the right direction, having a Circuit break API would be ideal for those non-transient scenarios.

**Comment by jesperkristensen** [comment]
I don't think it is possible to code custom logic that makes a function disable itself via the management API, because such logic will have to sit in the outermost try-catch to be robust. That try-catch is in the Functions runtime, so it would need to be implemented in the runtime itself.
