### ISSUE TITLE
How do we can pass the parameter (LimitToEndpoint=true) in cosmosclient object when we create the ComosDbtrigger using C#

### ISSUE THREAD

**Issue by bandarum** [Azure/azure-webjobs-sdk-extensions#728]
How do we can pass the parameter (LimitToEndpoint=true) in cosmosclient object when we create the ComosDbtrigger using C#

var client= new CosmosClient(endpoint,masterKey,CosmosClientOptions)
{
LimitToEndpoint=true,
ConnectionMode=Microsoft.Azure.Cosmos.ConnectionMode.GateWay
};

We are getting this error when we pass LimitToEndpoint in host.json.Please suggest the solution for us

host.json:
----------
"extensions":{
"cosmosDB" :{
"connectionMode":"Gateway",
LimitToEndpoint:true(problem occure in this place)
}
}

**Comment by ealsur** [comment]
That is not currently supported. Why do you want to pass LimitToEndpoint? Are you aware that that turns off the SDK regional availability? (https://docs.microsoft.com/en-us/azure/cosmos-db/troubleshoot-sdk-availability)

How do you propose to react once the regional endpoint is down due to an outage?
