### ISSUE TITLE
Document about how AddAzureStorageCoreServices reads configuration?

### ISSUE THREAD

**Issue by zhifzhan** [Azure/azure-webjobs-sdk-extensions#844]
(Not a bug)

Hello,

I'm using `Microsoft.Azure.WebJobs.Extensions 5.0.0` and storage based TimerTrigger.
From what I understand, `AddAzureStorageCoreServices` registers `AzureStorageProvider`, that provides `BlobContainerClient` to TimerTrigger.

It seems, `AzureStorageProvider` can read storage options (account name, service uri, or connection string) implicitly from `appsettings.json` or other configuration source. But I'm not sure how to configure them. 
Is there a document about the configuration convention? what configurations section and fields are used by `AzureStorageProvider`?

For example, to specify storage account, should I use:
`Storage.AccountName`,
or `Storage.ServiceUri`
or `Storage.BlobServiceUri`
or `AzureWebJobs.Extensions.Storage.Something`?

Thanks!

**Comment by bhagyshricompany** [comment]
@zhifzhan Thanks for reaching out.
In terms of which configuration section and fields are used by the AzureStorageProvider, the AccountName, AccountKey, and EndpointSuffix options are used by default. However, you can also specify the storage account using the ServiceUri or BlobServiceUri options instead of the AccountName and EndpointSuffix options. These options are located under the Storage section in the configuration file.

So to specify the storage account, you can use either Storage.AccountName or Storage.ServiceUri in your appsettings.json file. Both options will work with the AzureStorageProvider.

**Comment by zhifzhan** [comment]
@bhagyshricompany Thank you.

Our project already uses `Storage.ServiceUri` for dependency injection of `BlobServiceClient` (with `Microsoft.Extensions.Azure` package).
Happy to know WebJob can also leverage this config.
