### ISSUE TITLE
Cosmos DB trigger updates ContinuationToken on Exception

### ISSUE THREAD

**Issue by thomasvdb** [Azure/azure-webjobs-sdk-extensions#857]
#### Is your question related to a specific version? If so, please specify
Azure Functions v4

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All): 
C#

#### Question
I want to implement the Transactional Outbox pattern with the Azure Functions Cosmos DB trigger (https://learn.microsoft.com/en-us/azure/architecture/best-practices/transactional-outbox-cosmos).

When playing around with this setup, I still have some issues with Exception handling.
I've created a basic Azure Function project and a very simple Azure Function:

**Project file:**
```
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <AzureFunctionsVersion>V4</AzureFunctionsVersion>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.CosmosDB" Version="3.0.10" />
        <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.1.1" />
    </ItemGroup>
    <ItemGroup>
        <None Update="host.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="local.settings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>Never</CopyToPublishDirectory>
        </None>
    </ItemGroup>
</Project>

```

**Azure Function:**
```
public static class CosmosFunction
{
    [FunctionName("CosmosFunction")]
   // [FixedDelayRetry(5, "00:00:10")]
    public static async Task RunAsync([CosmosDBTrigger(
            databaseName: "Feed",
            collectionName: "Schedules",
            ConnectionStringSetting = "CosmosDbAccountEndpoint",
            LeaseCollectionName = "leases")]
        IReadOnlyList<Document> input, ILogger log)
    {
        throw new Exception("Test");
        
        if (input != null && input.Count > 0)
        {
            log.LogInformation("Documents modified " + input.Count);
            log.LogInformation("First document Id " + input[0].Id);
            
        }
    }
}
```

In this Function I just throw an Exception to mimic an unhandled Exception.
When starting this Function and updating an item in the Cosmos DB collection, I notice that the `ContinuationToken` in the _Leases_ collection is updated after the Exception is thrown.

```
{
    "id": "[redacted]",
    "_etag": "\"5600e691-0000-0d00-0000-64be24840000\"",
    "PartitionId": "0",
    "Owner": "[redacted]",
    "ContinuationToken": "\"328\"",
    "properties": {},
    [...]
}
```

I would expect that this `ContinuationToken` isn't updated?
When enabling the `FixedDelayRetry` attribute above the Function, the `ContinuationToken` isn't updated when it's retrying which seems fine.

If you, however, then stop the Azure Function (because you want to fix the issue), the `ContinuationToken` is updated when stopping the Azure Function because presumably it's exiting its retry loop. Also when it reaches its maximum retry count, the `ContinuationToken` is updated.

Is this expected behaviour? Is there any additional configuration needed to prevent this?
I'm testing this locally on macOS Ventura 13.4.1 with Azurite.

**Comment by bhagyshricompany** [comment]
you can try Exponential Backoff and Circuit Breaker: Instead of using FixedDelayRetry, you can implement your own retry logic with exponential backoff and a circuit breaker pattern. This approach provides better control over the retry behavior and helps prevent excessive retries in case of continuous failures.

**Comment by thomasvdb** [comment]
I’m not really concerned about excessive retries but more about the loss of Cosmos DB changes because the timestamp in the Leases container is updated even when the Azure Function failed. That doesn’t seem right?

**Comment by bhagyshricompany** [comment]
@mattchenderson  pls comment validate.

**Comment by thomasvdb** [comment]
@bhagyshricompany @mattchenderson Any update on this?

**Comment by ealsur** [comment]
You are using the Extension 3.X version:

```
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.CosmosDB" Version="3.0.10" />
```

The behavior of that extension is to advance the checkpoint even on unhandled exceptions and that is by design, like the Event Hub Trigger.

Extension 4.X added support for Retry Policies. So if your intent is to have the payload retried on an unhandled exception through Retry Policies, you should migrate to the newer version.

Having said that, be advised that event based Triggers by design do not retry on unhandled exceptions, otherwise there is a real possibility of an infinite Azure bill if you are on Consumption Plan and have a non-transient code bug throwing unhandled exceptions continuously. Reference: https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/troubleshoot-changefeed-functions#some-changes-are-missing-in-your-trigger

**Comment by thomasvdb** [comment]
Using a combination of retry policies and additional logging, it seems we can cover our use case.
